// <auto-generated />
using System;
using System.Numerics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RaffleIndexer.Data;

#nullable disable

namespace RaffleIndexer.Data.Migrations
{
    [DbContext(typeof(IndexerDbContext))]
    [Migration("20260903075332_MakeSettledAtTimeNullable")]
    partial class MakeSettledAtTimeNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RaffleIndexer.Data.Entry", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<long>("BlockNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("block_number");

                    b.Property<DateTimeOffset>("BlockTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("block_time");

                    b.Property<int>("LogIndex")
                        .HasColumnType("integer")
                        .HasColumnName("log_index");

                    b.Property<string>("PlayerAddress")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("player_address");

                    b.Property<int>("RoundId")
                        .HasColumnType("integer")
                        .HasColumnName("round_id");

                    b.Property<string>("TxHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tx_hash");

                    b.HasKey("Id")
                        .HasName("pk_entries");

                    b.HasIndex("PlayerAddress")
                        .HasDatabaseName("ix_entries_player_address");

                    b.HasIndex("RoundId")
                        .HasDatabaseName("ix_entries_round_id");

                    b.HasIndex("TxHash", "LogIndex")
                        .IsUnique()
                        .HasDatabaseName("ix_entries_tx_hash_log_index");

                    b.ToTable("entries", (string)null);
                });

            modelBuilder.Entity("RaffleIndexer.Data.IndexerCursor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("ChainHeadBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("chain_head_block");

                    b.Property<long>("LastIndexedBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("last_indexed_block");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cursor");

                    b.ToTable("cursor", (string)null);
                });

            modelBuilder.Entity("RaffleIndexer.Data.IndexerMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasColumnType("text")
                        .HasColumnName("key");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("Key")
                        .HasName("pk_metadata");

                    b.ToTable("metadata", (string)null);
                });

            modelBuilder.Entity("RaffleIndexer.Data.Round", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.Property<long>("OpenedAtBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("opened_at_block");

                    b.Property<DateTimeOffset>("OpenedAtTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_time");

                    b.Property<BigInteger?>("PrizeWei")
                        .HasColumnType("numeric(78,0)")
                        .HasColumnName("prize_wei");

                    b.Property<BigInteger?>("RequestId")
                        .HasColumnType("numeric(78,0)")
                        .HasColumnName("request_id");

                    b.Property<long?>("RequestedAtBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("requested_at_block");

                    b.Property<long?>("SettledAtBlock")
                        .HasColumnType("bigint")
                        .HasColumnName("settled_at_block");

                    b.Property<DateTimeOffset?>("SettledAtTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settled_at_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("WinnerAddress")
                        .HasColumnType("text")
                        .HasColumnName("winner_address");

                    b.HasKey("Id")
                        .HasName("pk_rounds");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_rounds_status");

                    b.HasIndex("WinnerAddress")
                        .HasDatabaseName("ix_rounds_winner_address");

                    b.ToTable("rounds", (string)null);
                });

            modelBuilder.Entity("RaffleIndexer.Data.Entry", b =>
                {
                    b.HasOne("RaffleIndexer.Data.Round", "Round")
                        .WithMany("Entries")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_entries_rounds_round_id");

                    b.Navigation("Round");
                });

            modelBuilder.Entity("RaffleIndexer.Data.Round", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
